Repository wafflestudio/siksha-ios, pull requests merged in 2025-08, with the labels that each got.

#28 feat: setting tab UI renewal
  Siksha.xcodeproj/project.pbxproj
  Siksha/AppDelegate.swift
  Siksha/Assets.xcassets/ArrowSmall.imageset/Arrow_small.svg
  Siksha/Assets.xcassets/ArrowSmall.imageset/Contents.json
  Siksha/Assets.xcassets/BigLogoEllipse.imageset/Contents.json
  Siksha/Assets.xcassets/BigLogoEllipse.imageset/Group 130.svg
  Siksha/Assets.xcassets/BigLogoEllipse.imageset/Group 131.svg
  Siksha/Assets.xcassets/BigLogoEllipse.imageset/Group 132.svg
  Siksha/Assets.xcassets/CheckCircle.imageset/Contents.json
  Siksha/Assets.xcassets/CheckCircle.imageset/notChecked.svg
  Siksha/Assets.xcassets/Checked.imageset/Contents.json
  Siksha/Assets.xcassets/Checked.imageset/checked-1.png
  Siksha/Assets.xcassets/Checked.imageset/checked-2.png
  Siksha/Assets.xcassets/Checked.imageset/checked.png
  Siksha/Assets.xcassets/Comment-new.imageset/Comment-new.svg
  Siksha/Assets.xcassets/Comment-new.imageset/Contents.json
  Siksha/Assets.xcassets/LogoEllipse.imageset/Contents.json
  Siksha/Assets.xcassets/LogoEllipse.imageset/Frame 188@2x 1.svg
  Siksha/Assets.xcassets/LogoEllipse.imageset/Frame 188@3x 1.svg
  Siksha/Assets.xcassets/LogoEllipse.imageset/Frame 189.svg
  Siksha/Assets.xcassets/LogoEllipse.imageset/Group 25.svg
  Siksha/Assets.xcassets/LogoEllipse.imageset/Group 26.svg
  Siksha/Assets.xcassets/LogoEllipse.imageset/Group 27.svg
  Siksha/Assets.xcassets/NotChecked.imageset/Contents.json
  Siksha/Assets.xcassets/NotChecked.imageset/notChecked-1.png
  Siksha/Assets.xcassets/NotChecked.imageset/notChecked-2.png
  Siksha/Assets.xcassets/NotChecked.imageset/notChecked.png
  Siksha/Assets.xcassets/RenewalArrow.imageset/Arrow.png
  Siksha/Assets.xcassets/RenewalArrow.imageset/Arrow@2x.png
  Siksha/Assets.xcassets/RenewalArrow.imageset/Arrow@3x.png
  Siksha/Assets.xcassets/RenewalArrow.imageset/Contents.json
  Siksha/Assets.xcassets/SemanticColor/Text/Bubble.colorset/Contents.json
  Siksha/ContentView.swift
  Siksha/FeatureFlag.swift
  Siksha/Library/Extensions/Color+SikshaColor.swift
  Siksha/Library/Extensions/Extensions.swift
  Siksha/Library/NavigationBarModifier.swift
  Siksha/Library/UIRepresentable/TextView.swift
  Siksha/Settings/AccountManageView.swift
  Siksha/Settings/Dummy.swift
  Siksha/Settings/FavoriteRestaurantOrderView.swift
  Siksha/Settings/InformationView.swift
  Siksha/Settings/MyPostView.swift
  Siksha/Settings/ProfileEditView.swift
  Siksha/Settings/RenewalSettingsView.swift
  Siksha/Settings/RenewalVOCView.swift
  Siksha/Settings/RestaurantOrderView.swift
  Siksha/Settings/SettingsView.swift
  Siksha/Settings/SettingsViewModel.swift
  Siksha/Settings/VOCView.swift
Labels: 디자인개선

#36 fix: Favorite-selected image set name
  Siksha/Assets.xcassets/Favorite-selected.imageset/Contents.json
  Siksha/Assets.xcassets/Favorite-selected.imageset/favoriteSelected.png
  Siksha/Assets.xcassets/Favorite-selected.imageset/favoriteSelected@2x.png
  Siksha/Assets.xcassets/Favorite-selected.imageset/favoriteSelected@3x.png
Labels: 버그

#25 feat: Mixpanel 도입 및 적용
  Siksha.xcodeproj/project.pbxproj
  Siksha.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Siksha/Analytics/AnalyticsEvent.swift
  Siksha/Analytics/AnalyticsKey.swift
  Siksha/Analytics/MixpanelAnalytics.swift
  Siksha/AppDelegate.swift
  Siksha/Library/Config.swift
  Siksha/Library/View Elements/MenuFilterView.swift
  Siksha/Main/MenuListView.swift
  Siksha/Main/MenuViewModel.swift
Labels: 기능추가
